"""
Consolidation JSONB Data Template and Constants for Brazilian Asset Classes.
Note: Static asset metadata such as CNPJ, sector, and governance belong to the 'assets' table,
while 'consolidations' stores purely the portfolio position snapshots.
"""
from typing import Dict, Any

# Empty default template for new consolidations
EMPTY_CONSOLIDATION_DATA_TEMPLATE: Dict[str, Any] = {
    "summary": {
        "total_invested": 0.00,
        "reference_currency": "BRL",
        "assets_count": 0,
    },
    "stocks": [],
    "funds": [],
    "fixed_income": [],
    "crypto": [],
    "international": [],
    "cash": [],
}

# Sample template populated with fictional data (3 items per category)
SAMPLE_CONSOLIDATION_DATA: Dict[str, Any] = {
    "summary": {
        "reference_year": 2025,
        "reference_date": "2025-12-31",
        "total_invested": 42150.00,
        "total_stocks_invested": 12500.00,
        "total_funds_invested": 6800.00,
        "reference_currency": "BRL",
        "assets_count": 15,
    },
    "stocks": [
        {
            "ticker": "XPTO3",
            "name": "XPTO Tecnologia S.A.",
            "quantity": 100.0,
            "average_price": 45.00,
            "type": "ON",
            "custody": "Corretora A",
            "currency": "BRL",
            "total_invested": 4500.00,
        },
        {
            "ticker": "ACME4",
            "name": "ACME Indústrias S.A.",
            "quantity": 200.0,
            "average_price": 22.50,
            "type": "PN",
            "custody": "Corretora A",
            "currency": "BRL",
            "total_invested": 4500.00,
        },
        {
            "ticker": "FOO3",
            "name": "Foo Energia S.A.",
            "quantity": 50.0,
            "average_price": 70.00,
            "type": "ON",
            "custody": "Corretora B",
            "currency": "BRL",
            "total_invested": 3500.00,
        },
    ],
    "funds": [
        {
            "ticker": "ABCD11",
            "name": "ABCD Logística FII",
            "quantity": 30.0,
            "average_price": 95.00,
            "type": "FII",
            "custody": "Corretora A",
            "currency": "BRL",
            "total_invested": 2850.00,
        },
        {
            "ticker": "EFGH11",
            "name": "EFGH Recebíveis FII",
            "quantity": 50.0,
            "average_price": 9.50,
            "type": "FII",
            "custody": "Corretora A",
            "currency": "BRL",
            "total_invested": 475.00,
        },
        {
            "ticker": "IJKL11",
            "name": "IJKL Crédito Agro Fiagro",
            "quantity": 40.0,
            "average_price": 86.88,
            "type": "FIAGRO",
            "custody": "Corretora B",
            "currency": "BRL",
            "total_invested": 3475.00,
        },
    ],
    "fixed_income": [
        {
            "name": "Tesouro Selic 2029",
            "issuer": "Tesouro Nacional",
            "type": "TREASURY",
            "indexer": "SELIC",
            "rate": "SELIC + 0.15%",
            "purchase_date": "2025-03-10",
            "maturity_date": "2029-03-01",
            "quantity": 1.0,
            "invested_amount": 5000.00,
            "current_value": 5120.00,
            "custody": "Corretora C",
            "currency": "BRL",
        },
        {
            "name": "CDB Banco Exemplo 120%",
            "issuer": "Banco Exemplo",
            "type": "CDB",
            "indexer": "CDI",
            "rate": "120% CDI",
            "purchase_date": "2025-01-15",
            "maturity_date": "2027-01-15",
            "quantity": 1.0,
            "invested_amount": 3000.00,
            "current_value": 3150.00,
            "custody": "Corretora C",
            "currency": "BRL",
        },
        {
            "name": "LCI Banco Fictício",
            "issuer": "Banco Fictício",
            "type": "LCI",
            "indexer": "CDI",
            "rate": "95% CDI",
            "purchase_date": "2025-06-01",
            "maturity_date": "2026-06-01",
            "quantity": 1.0,
            "invested_amount": 2000.00,
            "current_value": 2050.00,
            "custody": "Corretora C",
            "currency": "BRL",
        },
    ],
    "crypto": [
        {
            "ticker": "BTC",
            "name": "Bitcoin",
            "quantity": 0.01000000,
            "average_price": 350000.00,
            "custody": "Exchange X",
            "currency": "BRL",
            "total_invested": 3500.00,
        },
        {
            "ticker": "ETH",
            "name": "Ethereum",
            "quantity": 0.50000000,
            "average_price": 12000.00,
            "custody": "Exchange X",
            "currency": "BRL",
            "total_invested": 6000.00,
        },
        {
            "ticker": "SOL",
            "name": "Solana",
            "quantity": 10.0,
            "average_price": 850.00,
            "custody": "Exchange X",
            "currency": "BRL",
            "total_invested": 8500.00,
        },
    ],
    "international": [
        {
            "ticker": "MOCK",
            "name": "Mock S&P 500 ETF",
            "quantity": 3.0,
            "average_price": 500.00,
            "type": "ETF",
            "custody": "Corretora Int.",
            "currency": "USD",
            "total_invested": 1500.00,
        },
        {
            "ticker": "FAKE",
            "name": "Fake Total Market ETF",
            "quantity": 5.0,
            "average_price": 220.00,
            "type": "ETF",
            "custody": "Corretora Int.",
            "currency": "USD",
            "total_invested": 1100.00,
        },
        {
            "ticker": "TEST",
            "name": "Test Nasdaq 100 ETF",
            "quantity": 2.0,
            "average_price": 400.00,
            "type": "ETF",
            "custody": "Corretora Int.",
            "currency": "USD",
            "total_invested": 800.00,
        },
    ],
    "cash": [
        {
            "account": "Reserva de Emergência",
            "institution": "Banco Digital Exemplo",
            "amount": 5000.00,
            "currency": "BRL",
        },
        {
            "account": "Conta Corrente",
            "institution": "Banco Fictício",
            "amount": 2500.00,
            "currency": "BRL",
        },
        {
            "account": "Conta USD",
            "institution": "Corretora Int.",
            "amount": 300.00,
            "currency": "USD",
        },
    ],
}
