"""
Consolidation JSONB Data Template and Constants for Brazilian Asset Classes.
Note: Static asset metadata such as CNPJ, sector, and governance belong to the 'assets' table,
while 'consolidations' stores purely the portfolio position snapshots.
"""
from typing import Dict, Any

# Empty default template for new consolidations
EMPTY_CONSOLIDATION_DATA_TEMPLATE: Dict[str, Any] = {
    "summary": {
        "total_invested": 0.00,
        "reference_currency": "BRL",
        "assets_count": 0,
    },
    "stocks": [],
    "funds": [],
    "fixed_income": [],
    "crypto": [],
    "international": [],
    "cash": [],
}

# Standard template populated with Brazilian asset classes (excluding zero-balance assets & no CNPJ)
SAMPLE_CONSOLIDATION_DATA: Dict[str, Any] = {
    "summary": {
        "reference_year": 2025,
        "reference_date": "2025-12-31",
        "total_invested": 75034.95,
        "total_stocks_invested": 40845.46,
        "total_funds_invested": 8286.99,
        "reference_currency": "BRL",
        "assets_count": 26,
    },
    "stocks": [
        {
            "ticker": "ABCB4",
            "name": "Banco ABC Brasil S.A.",
            "quantity": 80.0,
            "average_price": 21.41,
            "type": "PN",
            "custody": "BTG",
            "currency": "BRL",
            "total_invested": 1712.80,
        },
        {
            "ticker": "BBAS3",
            "name": "Banco do Brasil S.A.",
            "quantity": 286.0,
            "average_price": 21.81,
            "type": "ON",
            "custody": "BTG",
            "currency": "BRL",
            "total_invested": 6237.66,
        },
        {
            "ticker": "BBSE3",
            "name": "BB Seguridade Participações S.A.",
            "quantity": 78.0,
            "average_price": 32.06,
            "type": "ON",
            "custody": "BTG",
            "currency": "BRL",
            "total_invested": 2500.68,
        },
        {
            "ticker": "CXSE3",
            "name": "Caixa Seguridade Participações S.A.",
            "quantity": 88.0,
            "average_price": 10.14,
            "type": "ON",
            "custody": "BTG",
            "currency": "BRL",
            "total_invested": 892.32,
        },
        {
            "ticker": "ISAE4",
            "name": "CTEEP - Cia Transmissão Energia Paulista",
            "quantity": 118.0,
            "average_price": 24.69,
            "type": "PN",
            "custody": "BTG",
            "currency": "BRL",
            "total_invested": 2913.42,
        },
        {
            "ticker": "ITSA3",
            "name": "Itaúsa S.A.",
            "quantity": 223.0,
            "average_price": 9.95,
            "type": "ON",
            "custody": "BTG",
            "currency": "BRL",
            "total_invested": 2218.85,
        },
        {
            "ticker": "ITSA4",
            "name": "Itaúsa S.A.",
            "quantity": 216.0,
            "average_price": 10.19,
            "type": "PN",
            "custody": "BTG",
            "currency": "BRL",
            "total_invested": 2201.04,
        },
        {
            "ticker": "ITUB3",
            "name": "Itaú Unibanco Holding S.A.",
            "quantity": 30.0,
            "average_price": 33.06,
            "type": "ON",
            "custody": "BTG",
            "currency": "BRL",
            "total_invested": 991.80,
        },
        {
            "ticker": "KLBN4",
            "name": "Klabin S.A.",
            "quantity": 738.0,
            "average_price": 4.04,
            "type": "PN",
            "custody": "BTG",
            "currency": "BRL",
            "total_invested": 2981.52,
        },
        {
            "ticker": "NEOE3",
            "name": "Neoenergia S.A.",
            "quantity": 151.0,
            "average_price": 19.22,
            "type": "ON",
            "custody": "BTG",
            "currency": "BRL",
            "total_invested": 2902.22,
        },
        {
            "ticker": "ODPV3",
            "name": "Odontoprev S.A.",
            "quantity": 100.0,
            "average_price": 10.82,
            "type": "ON",
            "custody": "BTG",
            "currency": "BRL",
            "total_invested": 1082.00,
        },
        {
            "ticker": "SAPR4",
            "name": "Cia Saneamento do Paraná - Sanepar",
            "quantity": 363.0,
            "average_price": 4.73,
            "type": "PN",
            "custody": "BTG",
            "currency": "BRL",
            "total_invested": 1716.99,
        },
        {
            "ticker": "SOJA3",
            "name": "Boa Safra Sementes S.A.",
            "quantity": 318.0,
            "average_price": 11.90,
            "type": "ON",
            "custody": "BTG",
            "currency": "BRL",
            "total_invested": 3784.20,
        },
        {
            "ticker": "UNIP6",
            "name": "Unipar Carbocloro S.A.",
            "quantity": 60.0,
            "average_price": 57.18,
            "type": "PN",
            "custody": "BTG",
            "currency": "BRL",
            "total_invested": 3430.80,
        },
        {
            "ticker": "VALE3",
            "name": "Vale S.A.",
            "quantity": 82.0,
            "average_price": 64.38,
            "type": "ON",
            "custody": "BTG",
            "currency": "BRL",
            "total_invested": 5279.16,
        },
    ],
    "funds": [
        {
            "ticker": "CNES11",
            "name": "FII Cenesp",
            "quantity": 4.0,
            "average_price": 42.41,
            "type": "FII",
            "custody": "BTG",
            "currency": "BRL",
            "total_invested": 169.64,
        },
        {
            "ticker": "CPTS11",
            "name": "Capitânia Securities II FII",
            "quantity": 78.0,
            "average_price": 8.26,
            "type": "FII",
            "custody": "BTG",
            "currency": "BRL",
            "total_invested": 644.28,
        },
        {
            "ticker": "GARE11",
            "name": "Guardian Real Estate FII",
            "quantity": 235.0,
            "average_price": 8.76,
            "type": "FII",
            "custody": "BTG",
            "currency": "BRL",
            "total_invested": 2058.60,
        },
        {
            "ticker": "KCRE11",
            "name": "Kinea Crédito Agro Fiagro",
            "quantity": 159.0,
            "average_price": 9.26,
            "type": "FIAGRO",
            "custody": "BTG",
            "currency": "BRL",
            "total_invested": 1472.34,
        },
        {
            "ticker": "KNCR11",
            "name": "Kinea Rendimentos Imobiliários FII",
            "quantity": 11.0,
            "average_price": 100.32,
            "type": "FII",
            "custody": "BTG",
            "currency": "BRL",
            "total_invested": 1103.52,
        },
        {
            "ticker": "PMLL11",
            "name": "Malls Brasil Plural FII (Recibo)",
            "quantity": 10.0,
            "average_price": 102.59,
            "type": "FII",
            "custody": "BTG",
            "currency": "BRL",
            "total_invested": 1025.90,
        },
        {
            "ticker": "XPML11",
            "name": "XP Malls FII",
            "quantity": 17.0,
            "average_price": 106.63,
            "type": "FII",
            "custody": "BTG",
            "currency": "BRL",
            "total_invested": 1812.71,
        },
    ],
    "fixed_income": [
        {
            "name": "Tesouro Selic 2029",
            "issuer": "Tesouro Nacional",
            "type": "TREASURY",
            "indexer": "SELIC",
            "rate": "SELIC + 0.15%",
            "purchase_date": "2024-01-15",
            "maturity_date": "2029-03-01",
            "quantity": 1.0,
            "invested_amount": 14750.00,
            "current_value": 15120.00,
            "custody": "INTER",
            "currency": "BRL",
        }
    ],
    "crypto": [
        {
            "ticker": "BTC",
            "name": "Bitcoin",
            "quantity": 0.02500000,
            "average_price": 350000.00,
            "custody": "Cold Wallet",
            "currency": "BRL",
            "total_invested": 8750.00,
        }
    ],
    "international": [
        {
            "ticker": "VOO",
            "name": "Vanguard S&P 500 ETF",
            "quantity": 5.0,
            "average_price": 480.50,
            "type": "ETF",
            "custody": "Avenue",
            "currency": "USD",
            "total_invested": 2402.50,
        }
    ],
    "cash": [
        {
            "account": "Reserva de Emergência",
            "institution": "Nubank",
            "amount": 10000.00,
            "currency": "BRL",
        }
    ],
}
